#!/bin/sh

printf "Remember %s!\n" "$@" > mail.tmp

curl -v --ssl-reqd \
  --url "$URL" \
  --user "$MAIL_FROM:$MAIL_PASSWORD" \
  --mail-from "$MAIL_FROM" \
  --mail-rcpt "$MAIL_TO" \
  --upload-file mail.tmp
