#!/bin/sh
#
# This script parses the sourcefile and creates / updates a crontab from it.
# It expects the following format:
# 01.01. Name

sourcefile=${1:-./birthdays}
crontab=${2:-./crontab}

# check for input file
[ -e "$sourcefile" ] || exit 1

# sort by date
sort -t . -k 2 "$sourcefile" > tmp && mv tmp "$sourcefile"

# extract dates and names
[ -e "$crontab" ] && rm "$crontab" && touch "$crontab"
while read -r; do
    awk -F. '{
        /*  trim leading whitespace                     */

        gsub(/^ */,"",$3);

        /*  translate into crontab format:              */
        /*  minute hour day month weekday command       */

        printf("0 0 %.2d %.2d * notify-send \"%s\"\n", $1, $2, $3);

    }' >> "$crontab"
done < "$sourcefile"
